baseURL = "https://rpdl.net/"
title = "rpdl.net"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = ""

# Main menu items
[menu]
  [[menu.main]]
    identifier = "news"
    name = "news"
    title = "news"
    url = "/news/"
    weight = -110
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = -100
  [[menu.main]]
    identifier = "donate"
    name = "donate"
    title = "donate"
    url = "/donate/"
    weight = -90
  [[menu.main]]
    identifier = "discord"
    name = "discord"
    title = "discord"
    url = "/discord/"
    weight = -80
  [[menu.main]]
    identifier = "newest"
    name = "newest"
    title = "newest"
    url = "https://dl.rpdl.net/torrents/recent"
    weight = -70

# Configuration Features
[params]
  description = "rpdl.net"
  header_title = "rpdl.net"
  header_subtitle = "Safely download games, FAST."
  home_image = "/images/logo.png"
  recent_posts = 0
  mainSections = ["posts", "post", "blog"]
  [params.style]
    backgroundColor = "#0f172a"
    fontColor = "white"
